// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storesqlc

import (
	"database/sql"
)

type FileTransfer struct {
	ID                   string
	BatchID              string
	SourceMachineID      string
	DestinationMachineID string
	InitiatingUserID     string
	SessionID            sql.NullString
	DeliveryClientID     sql.NullString
	Basename             string
	Size                 int64
	Sha256               string
	CommittedOffset      int64
	State                string
	ResultCode           sql.NullString
	ReceiptPath          sql.NullString
	CreatedAt            int64
	ExpiresAt            int64
}

type InputDecision struct {
	SessionID    string
	ClientID     string
	AttachmentID string
	Generation   int64
	InputID      string
	RequestHash  []byte
	Status       string
	BytesWritten int64
	ErrorCode    sql.NullString
	CreatedAt    int64
}

type OperationResult struct {
	OperationID string
	RequestHash []byte
	State       string
	Result      []byte
	ErrorCode   sql.NullString
	CompletedAt sql.NullInt64
	ExpiresAt   int64
}

type OutputEvent struct {
	SessionID     string
	StartSequence int64
	EndSequence   int64
	Channel       int64
	Data          []byte
}

type Session struct {
	ID               string
	Name             string
	Cwd              string
	CommandPath      string
	CommandArgs      []byte
	CommandEnv       []byte
	Columns          int64
	Rows             int64
	State            string
	Generation       int64
	ExitCode         sql.NullInt64
	ExitSignal       sql.NullString
	ExitedAt         sql.NullInt64
	EarliestSequence int64
	LatestSequence   int64
	CreatedAt        int64
	UpdatedAt        int64
}
