// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions(id,name,cwd,command_path,command_args,command_env,columns,rows,state,generation,exit_code,exit_signal,exited_at,earliest_sequence,latest_sequence,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateSessionParams struct {
	ID               string
	Name             string
	Cwd              string
	CommandPath      string
	CommandArgs      []byte
	CommandEnv       []byte
	Columns          int64
	Rows             int64
	State            string
	Generation       int64
	ExitCode         sql.NullInt64
	ExitSignal       sql.NullString
	ExitedAt         sql.NullInt64
	EarliestSequence int64
	LatestSequence   int64
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.Cwd,
		arg.CommandPath,
		arg.CommandArgs,
		arg.CommandEnv,
		arg.Columns,
		arg.Rows,
		arg.State,
		arg.Generation,
		arg.ExitCode,
		arg.ExitSignal,
		arg.ExitedAt,
		arg.EarliestSequence,
		arg.LatestSequence,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteClosedSession = `-- name: DeleteClosedSession :execrows
DELETE FROM sessions WHERE id=? AND state IN ('exited','closed')
`

func (q *Queries) DeleteClosedSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteClosedSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredOperations = `-- name: DeleteExpiredOperations :exec
DELETE FROM operation_results WHERE expires_at<=?
`

func (q *Queries) DeleteExpiredOperations(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOperations, expiresAt)
	return err
}

const expiredFileTransfers = `-- name: ExpiredFileTransfers :many
SELECT id, batch_id, source_machine_id, destination_machine_id, initiating_user_id, session_id, delivery_client_id, basename, size, sha256, committed_offset, state, result_code, receipt_path, created_at, expires_at FROM file_transfers WHERE expires_at<=? AND state IN ('created','uploading','published','pending') ORDER BY expires_at,id LIMIT 100
`

func (q *Queries) ExpiredFileTransfers(ctx context.Context, expiresAt int64) ([]FileTransfer, error) {
	rows, err := q.db.QueryContext(ctx, expiredFileTransfers, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileTransfer
	for rows.Next() {
		var i FileTransfer
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.SourceMachineID,
			&i.DestinationMachineID,
			&i.InitiatingUserID,
			&i.SessionID,
			&i.DeliveryClientID,
			&i.Basename,
			&i.Size,
			&i.Sha256,
			&i.CommittedOffset,
			&i.State,
			&i.ResultCode,
			&i.ReceiptPath,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fileTransfer = `-- name: FileTransfer :one
SELECT id, batch_id, source_machine_id, destination_machine_id, initiating_user_id, session_id, delivery_client_id, basename, size, sha256, committed_offset, state, result_code, receipt_path, created_at, expires_at FROM file_transfers WHERE id=?
`

func (q *Queries) FileTransfer(ctx context.Context, id string) (FileTransfer, error) {
	row := q.db.QueryRowContext(ctx, fileTransfer, id)
	var i FileTransfer
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.SourceMachineID,
		&i.DestinationMachineID,
		&i.InitiatingUserID,
		&i.SessionID,
		&i.DeliveryClientID,
		&i.Basename,
		&i.Size,
		&i.Sha256,
		&i.CommittedOffset,
		&i.State,
		&i.ResultCode,
		&i.ReceiptPath,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const fileTransfersByBatch = `-- name: FileTransfersByBatch :many
SELECT id, batch_id, source_machine_id, destination_machine_id, initiating_user_id, session_id, delivery_client_id, basename, size, sha256, committed_offset, state, result_code, receipt_path, created_at, expires_at FROM file_transfers WHERE batch_id=? ORDER BY created_at,id
`

func (q *Queries) FileTransfersByBatch(ctx context.Context, batchID string) ([]FileTransfer, error) {
	rows, err := q.db.QueryContext(ctx, fileTransfersByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileTransfer
	for rows.Next() {
		var i FileTransfer
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.SourceMachineID,
			&i.DestinationMachineID,
			&i.InitiatingUserID,
			&i.SessionID,
			&i.DeliveryClientID,
			&i.Basename,
			&i.Size,
			&i.Sha256,
			&i.CommittedOffset,
			&i.State,
			&i.ResultCode,
			&i.ReceiptPath,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperation = `-- name: GetOperation :one
SELECT operation_id,request_hash,state,result,COALESCE(error_code,''),completed_at,expires_at FROM operation_results WHERE operation_id=?
`

type GetOperationRow struct {
	OperationID string
	RequestHash []byte
	State       string
	Result      []byte
	ErrorCode   string
	CompletedAt sql.NullInt64
	ExpiresAt   int64
}

func (q *Queries) GetOperation(ctx context.Context, operationID string) (GetOperationRow, error) {
	row := q.db.QueryRowContext(ctx, getOperation, operationID)
	var i GetOperationRow
	err := row.Scan(
		&i.OperationID,
		&i.RequestHash,
		&i.State,
		&i.Result,
		&i.ErrorCode,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listInputDecisions = `-- name: ListInputDecisions :many
SELECT session_id,client_id,attachment_id,generation,input_id,request_hash,status,bytes_written,COALESCE(error_code,''),created_at FROM input_decisions WHERE session_id=? ORDER BY generation,created_at
`

type ListInputDecisionsRow struct {
	SessionID    string
	ClientID     string
	AttachmentID string
	Generation   int64
	InputID      string
	RequestHash  []byte
	Status       string
	BytesWritten int64
	ErrorCode    string
	CreatedAt    int64
}

func (q *Queries) ListInputDecisions(ctx context.Context, sessionID string) ([]ListInputDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInputDecisions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInputDecisionsRow
	for rows.Next() {
		var i ListInputDecisionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ClientID,
			&i.AttachmentID,
			&i.Generation,
			&i.InputID,
			&i.RequestHash,
			&i.Status,
			&i.BytesWritten,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
SELECT operation_id,request_hash,state,result,COALESCE(error_code,''),completed_at,expires_at FROM operation_results ORDER BY CASE state WHEN 'pending' THEN 0 ELSE 1 END,completed_at ASC LIMIT ?
`

type ListOperationsRow struct {
	OperationID string
	RequestHash []byte
	State       string
	Result      []byte
	ErrorCode   string
	CompletedAt sql.NullInt64
	ExpiresAt   int64
}

func (q *Queries) ListOperations(ctx context.Context, limit int64) ([]ListOperationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOperations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOperationsRow
	for rows.Next() {
		var i ListOperationsRow
		if err := rows.Scan(
			&i.OperationID,
			&i.RequestHash,
			&i.State,
			&i.Result,
			&i.ErrorCode,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id,name,cwd,command_path,command_args,command_env,columns,rows,state,generation,exit_code,COALESCE(exit_signal,''),exited_at,earliest_sequence,latest_sequence,created_at,updated_at FROM sessions ORDER BY name
`

type ListSessionsRow struct {
	ID               string
	Name             string
	Cwd              string
	CommandPath      string
	CommandArgs      []byte
	CommandEnv       []byte
	Columns          int64
	Rows             int64
	State            string
	Generation       int64
	ExitCode         sql.NullInt64
	ExitSignal       string
	ExitedAt         sql.NullInt64
	EarliestSequence int64
	LatestSequence   int64
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cwd,
			&i.CommandPath,
			&i.CommandArgs,
			&i.CommandEnv,
			&i.Columns,
			&i.Rows,
			&i.State,
			&i.Generation,
			&i.ExitCode,
			&i.ExitSignal,
			&i.ExitedAt,
			&i.EarliestSequence,
			&i.LatestSequence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingFileTransfers = `-- name: PendingFileTransfers :many
SELECT id, batch_id, source_machine_id, destination_machine_id, initiating_user_id, session_id, delivery_client_id, basename, size, sha256, committed_offset, state, result_code, receipt_path, created_at, expires_at FROM file_transfers WHERE delivery_client_id=? AND session_id=? AND state='pending' AND expires_at>? ORDER BY created_at,id LIMIT ?
`

type PendingFileTransfersParams struct {
	DeliveryClientID sql.NullString
	SessionID        sql.NullString
	ExpiresAt        int64
	Limit            int64
}

func (q *Queries) PendingFileTransfers(ctx context.Context, arg PendingFileTransfersParams) ([]FileTransfer, error) {
	rows, err := q.db.QueryContext(ctx, pendingFileTransfers,
		arg.DeliveryClientID,
		arg.SessionID,
		arg.ExpiresAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileTransfer
	for rows.Next() {
		var i FileTransfer
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.SourceMachineID,
			&i.DestinationMachineID,
			&i.InitiatingUserID,
			&i.SessionID,
			&i.DeliveryClientID,
			&i.Basename,
			&i.Size,
			&i.Sha256,
			&i.CommittedOffset,
			&i.State,
			&i.ResultCode,
			&i.ReceiptPath,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replayOutput = `-- name: ReplayOutput :many
SELECT channel,start_sequence,end_sequence,data FROM output_events WHERE session_id=? AND end_sequence>? ORDER BY start_sequence
`

type ReplayOutputParams struct {
	SessionID   string
	EndSequence int64
}

type ReplayOutputRow struct {
	Channel       int64
	StartSequence int64
	EndSequence   int64
	Data          []byte
}

func (q *Queries) ReplayOutput(ctx context.Context, arg ReplayOutputParams) ([]ReplayOutputRow, error) {
	rows, err := q.db.QueryContext(ctx, replayOutput, arg.SessionID, arg.EndSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReplayOutputRow
	for rows.Next() {
		var i ReplayOutputRow
		if err := rows.Scan(
			&i.Channel,
			&i.StartSequence,
			&i.EndSequence,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetOversizedOperations = `-- name: ResetOversizedOperations :exec
UPDATE operation_results SET state='pending',result=NULL,error_code=NULL,completed_at=NULL WHERE length(result)>CAST(?1 AS INTEGER)
`

func (q *Queries) ResetOversizedOperations(ctx context.Context, maxBytes int64) error {
	_, err := q.db.ExecContext(ctx, resetOversizedOperations, maxBytes)
	return err
}

const sessionBounds = `-- name: SessionBounds :one
SELECT earliest_sequence,latest_sequence FROM sessions WHERE id=?
`

type SessionBoundsRow struct {
	EarliestSequence int64
	LatestSequence   int64
}

func (q *Queries) SessionBounds(ctx context.Context, id string) (SessionBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, sessionBounds, id)
	var i SessionBoundsRow
	err := row.Scan(&i.EarliestSequence, &i.LatestSequence)
	return i, err
}
